name: Golangci-lint check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    
    - name: lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true
      

