name: Static Checks and Linting

concurrency:
  group: static-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    
    - name: lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true
          args: --timeout 5m --out-format=github-actions > ./op.txt
          run: |
            if [[ -s gofmt.out ]]; then
              echo "The following files were found to have formatting deviations:"
              cat gofmt.out
              exit 1
            fi
      

